### ISSUE TITLE
Can't use book to enchant in survival

### ISSUE THREAD

**Issue by grandpaslab** [Geolykt/EnchantmentsPlus#24] opened 2020-12-17 03:27 UTC
We've installed EnchantmentsPlus on our 1.16.1 server, and we've found that we can't use a book to enchant any item in survival mode. Works fine in creative. Are we doing something wrong, or is it broken?

**Comment by Geolykt** [comment] 2020-12-17 08:47
Could be a permission issue, could be something else. I believe that it is likely something to do with incompatible tools.

**Comment by Geolykt** [comment] 2020-12-18 16:45
Could you provide your configurations? It helps me to reproduce your issue. Additionally I would like to know if you are using CB (please don't), Spigot or Paper

**Comment by grandpaslab** [comment] 2020-12-18 17:51
configs: https://drive.google.com/drive/folders/1Y2rkJrrPimmqexcCafLvjDJPNr9C1j9k?usp=sharing

We're using Spigot.

**Comment by Geolykt** [comment] 2020-12-18 17:55
If I'm not fully wrong there's currently a bug with our code within spigot which is "fixed" under paper (or at least was a month ago).
 Fixing it would require some non-standard things, although isn't impossible

**Comment by Geolykt** [comment] 2020-12-18 17:59
However your issue is based on the config and can be fixed by adding 
`    - "ENCHANTED_BOOK"`
to tools.axe, tools.pickaxe, etc. in the magicCompat.yml. It's an oversight from me that I did a few versions ago, which is why it's a bit borked.

So it would look something like
```yml

[...]
    - "DIAMOND_SWORD"
    - "NETHERITE_SWORD" # 1.16 and beyond
    - "FISHING_ROD"
    - "BOW"
    - "SHEARS"
    - "FLINT_AND_STEEL"
    - "ENCHANTED_BOOK"
  axe:
    - "WOODEN_AXE"
    - "STONE_AXE"
    - "IRON_AXE"
    - "GOLDEN_AXE"
    - "DIAMOND_AXE"
    - "NETHERITE_AXE" # 1.16 and beyond
    - "ENCHANTED_BOOK"
  pickaxe:
    - "WOODEN_PICKAXE"
    - "STONE_PICKAXE"
    - "IRON_PICKAXE"
    - "GOLDEN_PICKAXE"
    - "DIAMOND_PICKAXE"
    - "NETHERITE_PICKAXE" # 1.16 and beyond
    - "ENCHANTED_BOOK"
[...]
```

**Comment by grandpaslab** [comment] 2020-12-18 18:25
updated config: https://drive.google.com/file/d/1nRIgtwpBVhFhBN8ZRrDCeaOXiEirlUca/view?usp=sharing

Still not working. Is anything required other than changing the config and restarting the server?

[Screenshot](https://drive.google.com/file/d/1-TjCH6owF4uK-X7BfliU5-AfkeDMCrX_/view?usp=sharing). Looks like it's going to work, but clicking the button does nothing.

**Comment by Geolykt** [comment] 2020-12-18 18:29
That's the spigot part of the bug

**Comment by grandpaslab** [comment] 2020-12-18 18:42
Ah, OK. Can you update your readme? Would've saved me a couple days if the readme said Paper was required.

**Comment by Geolykt** [comment] 2020-12-18 18:47
Paper isn't required at all

**Comment by grandpaslab** [comment] 2020-12-18 19:27
OK, but the readme says "The current version of this plugin is fully compatible with Spigot version 1.16.1, 1.16.2 and 1.16.3"
and it's not.

**Comment by kyematzen** [comment] 2021-01-08 16:12
I'll take a look at this later and see if we can get this resolved.

**Comment by kyematzen** [comment] 2021-01-25 16:48
It's been a while since I last updated or forked the project.

I've been heavily researching into what the issue is inside of the plugin. I can only really come up with the idea that NBT could be factoring into an issue.

**Comment by Geolykt** [comment] 2021-01-25 17:35
I'll might test which version of spigot introduced the issue today (because as far as I know this hasn't been always like that) - hopefully this will get us more information on this

**Comment by Geolykt** [comment] 2021-02-26 09:21
No longer marked as wontfix as this issue has regressed to also affect Paper

**Closed** 2021-02-26 19:24 UTC
Labels: bug:confirmed, compatibility:minecraft
