### ISSUE TITLE
enchantment table

### ISSUE THREAD

**Issue by ramanzxo** [Geolykt/EnchantmentsPlus#139] opened 2023-07-20 17:49 UTC
is there anyway to disable geeting the enchantment through enchantment table , because on my server i want to sell these enchantments instead of other people using it.thankyou.

**Comment by Geolykt** [comment] 2023-07-20 17:51
Duplicate of https://github.com/Geolykt/EnchantmentsPlus/issues/138.
See the answer there

**Closed as not planned by Geolykt** 2023-07-20 17:51 UTC
Labels: duplicate, question

**Comment by ramanzxo** [comment] 2023-07-20 17:55
okay thankyou
