### ISSUE TITLE
1.16.5 / 3.1.4  Enchantments Allowed on Wrong Tools / Blocks in Anvil

### ISSUE THREAD

**Issue by iFalcon720** [Geolykt/EnchantmentsPlus#45] opened 2021-03-23 20:01 UTC
Paper-566
Was also an issue in 3.1.1 before I updated to 3.1.4.

I'm able to apply enchantments to disallowed tools in an anvil(i.e Transformation I on a shovel, Shred on a piece of cobblestone, etc)
Tested in survival and creative, with and without OP
I've also done some testing with combining enchanted books (given using the /ench give command) and at least combining 2 bounce 1 books results in an enchanted book with no 'lore' or enchantments listed.

**Comment by Geolykt** [comment] 2021-03-23 20:27
I am unable to reproduce this issue, could you send me your patches.yml?

**Comment by iFalcon720** [comment] 2021-03-23 21:08
https://pastebin.com/qkXnTgxq
I believe its unedited from default, however it was made in a previous version, 3.1.1 I believe

**Comment by Geolykt** [comment] 2021-03-23 21:24
I can reproduce this now and I have no real Idea why.
And this opens a whole new can of worms (was able to get bane of arthropods on a shovel, which is strange to say the least), I hope I'll get these resolved till tomorrow, or actually understand what causes these issues.

**Comment by Geolykt** [comment] 2021-03-23 21:36
Sometimes I am really an idiot. This is the third time that I think that ~~Pierce~~ Piercing is not a vanilla enchantment.

In short, I am not able to reproduce it, but I'll still leave this issue open as from what I'm gathering it's a duplicate of #42 or at least related to it which means that the issue does exist, but I am unable to reproduce it on my machine (TM)

**Comment by iFalcon720** [comment] 2021-03-23 21:44
Just to clarify Pierce is definitely from the plugin, while Piercing I - IV is vanilla for crossbows ^^
If that doesn't change anything I'll keep testing things and see if anything else could be causing my problems.

**Comment by Geolykt** [comment] 2021-03-23 22:05
Well, turns out that that was an intended vanilla mechanic is creative (absolutely forgot about it), But hey, at least the code is now written, so if for some reason someone tries to merge illegal enchantment now it will now be ignored by the plugin.
Could you provide screenshots about your issue? I think I might misinterpret it so it's best if I know for sure what (or at least if soemthing) went wrong there

**Comment by iFalcon720** [comment] 2021-03-23 22:38
Here's two short videos, first is putting Bind on a plank, second is two bounce I books resulting in a blank enchanted book.
These books were given using the command "/ench give (name) book bind / bounce"
https://i.gyazo.com/8433b094028effd5912e26aa732c7504.mp4

https://i.gyazo.com/e421b574b90ad4c317741e112578d250.mp4

~~I've also looked through my plugins and the only one I could see causing issues is AureliumSkills, which adds a forging skill that gives xp / cost reductions based on using an anvil.~~

Testing without AureliumSkills has the same issues.

**Comment by iFalcon720** [comment] 2021-04-05 15:32
@Geolykt Has there been any luck in finding a fix? I'm still having the issue even on a clean server with only EnchantmentsPlus added with Paper 581 / 1.16.5, so I can't imagine its another plugin interfering

**Comment by Geolykt** [comment] 2021-04-05 16:05
Not really, I will try to reproduce it  it one last time, but chances are that I have to make a really stupid "fix" like for #28

**Closed as completed** 2021-04-05 19:25 UTC
Labels: bug:resolved, bug:confirmed
