### ISSUE TITLE
Books with the new enchantments are unable to be used at an anvil

### ISSUE THREAD

**Issue by HungryHungrySnorlax** [Geolykt/EnchantmentsPlus#78] opened 2021-06-25 05:16 UTC
Hey, just recently started a new 1.17 server and me and my players have found that any enchanted books that have Zenchantment enchantments on them can not be used at an anvil to transfer the enchantment. Anvils still work fine for any vanilla enchantments. When attempting to add one of the plugin enchantments it doesn't even show a level requirement. All of the new enchantments also work fine when put directly on an item from an enchanting table.
![Screenshot 2021-06-25 010300](https://user-images.githubusercontent.com/29970749/123373173-efac1980-d552-11eb-88fe-5add2cd59fb1.png)
![Screenshot 2021-06-25 011358](https://user-images.githubusercontent.com/29970749/123373183-f3d83700-d552-11eb-9eef-427d6ae782a1.png)

**Comment by Geolykt** [comment] 2021-06-25 13:51
~~Likely duplicate of #24; the workaround is to set the `1xx-anvil-merger` property of the patches.yml file to true.
In case that you are not using spigot let me know so I can reopen this issue.
That being said, any developer may still introduce a proper fix, but I personally was unable to find one.~~

Actually, reading more about it it looks like an issue that got fixed ages ago; please provide `/ench info` output and `/canihasbukkit` output so I can diagnose this issue to the fullest extent

**Closed as completed** 2021-06-25 13:51 UTC
Labels: duplicate
