### ISSUE TITLE
Combine Enchanted Books to Tools in Anvil

### ISSUE THREAD

**Issue by igummie** [Geolykt/EnchantmentsPlus#15] opened 2020-10-23 18:06 UTC
I'm not able to combine an enchanted book onto any of my tools or armor at an anvil

**Comment by Geolykt** [comment] 2020-10-23 18:25
Thanks for the Bug report, however a bit more information is needed so it can be processed accordingly.

a) What is the current Plugin Version?
b) What were the previous plugin Versions?
c) What is the exact Server Version? (CB is updated multiple times a day — LATEST is a very inacurate description)
d) When was the patches.yml/magicCompat.yml last reset?
e) If the Plugin doesn't use default settings, which changes were made to them?
f) Screenshots? (if applicable)

I highly assume that it's an User input issue, but I won't outright close the issue as of now (wouldn't be the first time that my first thoughts were wrong)

**Comment by igummie** [comment] 2020-10-23 18:46
a) 2.1.4
b) first install
c) paper-git-244
d) I installed the plugin yesterday
e) default settings
![image](https://user-images.githubusercontent.com/25012134/97042023-74671380-153e-11eb-8082-116023e78603.png)
![image](https://user-images.githubusercontent.com/25012134/97042041-7af58b00-153e-11eb-9002-1f43081f59cc.png)

**Comment by igummie** [comment] 2020-10-23 18:46
also no worries. Probably is user error. Non of the players on my server including I could figure it out

**Comment by Geolykt** [comment] 2020-10-23 18:48
It's an user error. Update to v2.1.5 and delte the magicCompat.yml (update can be found at GitHub or SpigotMC)

**Comment by igummie** [comment] 2020-10-23 18:51
where is v2.1.5

**Comment by Geolykt** [comment] 2020-10-23 18:55
Oh oof, mistook v2.1.4 as v2.1.3 (where the exact issue persisted) because I forgot that v2.1.5 is still indev. Either way, I'll attempt to reproduce it. It's likely a duplicate of another issue which has been already fixed. Try damaging the source item first.

**Comment by igummie** [comment] 2020-10-23 18:58
no dice. 
![image](https://user-images.githubusercontent.com/25012134/97043042-f1df5380-153f-11eb-97cc-485a746b4c34.png)
however i just found another bug trying to put it on a damged pic with enchants already on it
![image](https://user-images.githubusercontent.com/25012134/97043107-0885aa80-1540-11eb-9243-fc1b5002e231.png)
however it doesn't actually add bind to the picaxe but addes some blank null value I assume
![image](https://user-images.githubusercontent.com/25012134/97043247-23581f00-1540-11eb-9fd4-24915059708a.png)

**Comment by Geolykt** [comment] 2020-10-24 12:09
Did some tests and I was able to reproduce it. As the class that was in charge of the merging is hardly maintainable I decided to rewrite it. However I came to the same issue, but I now know where the issue is and how it can be fixed.

The exact issue lies in that the default Enchantment getter automatically returns an empty list for enchanted books as it's not in the allowlist, to fix the issue following things can be performed:
  - Use a primitive getter such as PR47-lore or lwNBT (can be set within the patches.yml)
  - Add the book entry under getterAllow within the patches.yml

The issue will be resolved under v2.1.5, but in the meantime it can be fixed via the actions above.

**Closed by Geolykt** 2020-10-24 12:09 UTC
Labels: bug:possible
