### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by scottyboii** [Geolykt/EnchantmentsPlus#23] opened 2020-12-16 23:44 UTC
Hey I contacted you about this on Discord previously, but since your account was deleted I thought it's best to move it to here.

Enchantments Plus v2.2.2
Paper Spigot 184

![image](https://user-images.githubusercontent.com/32883419/102419548-d8b2ca80-3ff7-11eb-8eb1-8ccff9c46a3d.png)

![image](https://user-images.githubusercontent.com/32883419/102419751-5676d600-3ff8-11eb-9d45-b31a798647ef.png)

**Comment by Geolykt** [comment] 2020-12-18 16:27
I've looked at the issue for quit a while now, however I'm not sure how to resolve this, neither do I have an idea why the config is null (which is the cause of the NPE). I could just catch the exception and after x amount of triggers restart the server, which would theoretically "fix" the issue, but would be a hacky workaround.
On the bright side I could change such as system to report exceptions automatically, but I would let it stay how it currently is.

If anyone has an idea how to fix this, or could provide more insight on this, feel free to do so.

**Comment by Geolykt** [comment] 2020-12-18 16:38
Hey, could you search for "Error parsing config for world" or "Error parsing config for enchantment" in the log next time this occurs?

**Comment by scottyboii** [comment] 2020-12-18 21:23
![image](https://user-images.githubusercontent.com/32883419/102662688-3883af80-4177-11eb-8d4d-2e71b80e7704.png)
Continues for a lot longer, this is just after the error happened one time earlier today.

**Comment by Geolykt** [comment] 2020-12-18 21:27
Okay this will help.
 I recommend for you to revisit that configuration (delete it and let it regenerate if you don't need it). The bug can be reproduced by entering this world (I think).
 I will look if I can help in this debug process in the future, but meh.

**Comment by scottyboii** [comment] 2020-12-18 21:29
Delete the config within the enchantment+ file right?

**Comment by Geolykt** [comment] 2020-12-18 21:31
yes

**Comment by scottyboii** [comment] 2020-12-18 21:41
Just confirming, to disable an enchant is it 
Probability: -1.0
or
Probability: -1

**Comment by Geolykt** [comment] 2020-12-18 21:52
-1.0

**Comment by scottyboii** [comment] 2020-12-18 21:55
Alright thank you, will let you know if the issue happens again. :D

**Comment by scottyboii** [comment] 2020-12-19 00:37
The issue is still happening but I think it could be to do with other worlds as well as the one I had already done

Could it be an issue that our config version was only 1.0.0?

I'll regen all configs in the morning and let you know if it happens again.

**Comment by Geolykt** [comment] 2020-12-19 09:36
The configuration version doesn't really matter as we haven't added anything breaking (there was a minor addition (the AOE), but that defaults).
Now, I could be wrong that misconfiguration is at fault, but I highly assume it is

**Comment by Geolykt** [comment] 2020-12-25 15:06
Is it still an issue for you or can I close the Issue?

**Comment by scottyboii** [comment] 2020-12-26 17:53
I haven't seen it happening, I just visited every world and it seems to be fine now.

Go ahead and close, I can reopen if we notice it again! :D 


Thank you again for your help :)

**Closed** 2020-12-26 21:21 UTC
Labels: bug:confirmed
