### ISSUE TITLE
When will the next version with fixed issues be released? I hope the cooldown is fixed

### ISSUE THREAD

**Issue by eyesonme1212** [Geolykt/EnchantmentsPlus#112] opened 2022-01-16 07:26 UTC
When will the next version with fixed issues be released? I hope the cooldown is fixed

**Comment by Geolykt** [comment] 2022-01-16 12:05
The last commit was back in november 2021 and I have been regularly answering issues, it isn't too hard to tell that development is indefintely halted.
The biggest issue was that for a long time there was no incentive to update the project as I did not use it myself and as such I was relying solely on github issues to report bug reports. It was only a matter of time until I started a project that I had more fun with, which I now have for a good year. The fact that anvil merging proved to be impossible to fix killed of the motivation of working on EnchantmentsPlus entirely. I still have a glimmer of hope that I know the solution to resolve it, however If it would fail I would get disappointed again, which I do not like either.

That being said, there is still light at the end of the tunnel as I recently opened my own server and will look into integrating this plugin into it, though I'd like to fix all the known bugs beforehand, but that requires a lot of testing and time, which is a chore I do not wish to do for now.
<hr />

I remember there being an issue about cooldowns (which I cannot find for some reason, strange), but could you specify the cooldown not being fixed issue further?

**Comment by eyesonme1212** [comment] 2022-01-16 12:26
I don't know. It's just that putting a number in the cooldown in the folder doesn't apply. I don't know what is wrong.
I also hope that this plugin will serve you for a long time.

**Comment by Geolykt** [comment] 2022-01-16 12:39
Yeah then that is likely the issue I have heard about. I'll keep this issue open so I do not loose track of the cooldown issue

**Comment by Geolykt** [comment] 2022-01-28 16:34
I cannot reproduce it with any of the 5 enchantments I tested, which enchantments exactly are affected in your testing?

**Comment by eyesonme1212** [comment] 2022-01-28 18:41
Yes, all magic spells don't apply to cool time.

**Comment by Geolykt** [comment] 2022-01-28 22:10
This is not what I am seeing... odd.

Works on my machine (TM)

**Comment by eyesonme1212** [comment] 2022-01-29 02:32
Does the cool time work normally?

**Comment by eyesonme1212** [comment] 2022-01-29 05:11
![Uploading 20220129_141113.jpg…]()

**Comment by eyesonme1212** [comment] 2022-01-29 05:16
![20220129_141113](https://user-images.githubusercontent.com/91815395/151648460-1c9431e6-5923-4302-abc1-b333738abe3f.jpg)

**Comment by eyesonme1212** [comment] 2022-01-29 05:36
If it's just my own problem, is there a possibility of collision with other plugins? It doesn't come out on the log.

If it's my problem, I'll attach my server log.  T.T

**Comment by Geolykt** [comment] 2022-01-29 11:43
Cannot reproduce. Keep in mind that a cooldown of 200 is around 0.2s, which you would not spot that easily with this enchantment. This is different in upstream where cooldowns are in ticks instead.

I'd say that this issue was caused by an user error and therefore I am closing it since I cannot reproduce this issue

**Closed as completed by Geolykt** 2022-01-29 11:43 UTC
