### ISSUE TITLE
Luck of the sea does not work (1.16.3, running in Paper of that version)

### ISSUE THREAD

**Issue by Smash-Nerd** [Geolykt/EnchantmentsPlus#25] opened 2020-12-17 20:04 UTC
I certainly get more junk, but Luck of the Sea itself does not pull any enchanted books anymore.

**Comment by Geolykt** [comment] 2020-12-17 20:05
Pretty much impossible

**Comment by Smash-Nerd** [comment] 2020-12-17 20:08
I have no idea how that helps me in my current situation. i'll try reinstalling the plugin.

**Comment by Geolykt** [comment] 2020-12-17 20:21
The plugin does not alter fishing drops at all, I could investigate the issue further, but it's very unlikely that that is the case.
Are any enchantments on the rod? If no, then the issue is not worthy of being reopened without further proof, else, well then there is a chance that the plugin is actually at fault here

**Comment by Smash-Nerd** [comment] 2020-12-17 20:23
I'm doing a pretty big fishing session right now and comparing my loot with the actual statistics found here
https://minecraft.gamepedia.com/Fishing#Junk_and_treasure
I'll respond to this comment with my findings, but so far, no books, tools, or anything. I've gotten more junk that tools, and Junk is FAR less likely to get than said tools.

**Comment by Geolykt** [comment] 2020-12-17 20:28
It wouldn't (or at least) shouldn't mess with it at all if you were using Zenchantments with 1.15.2 or NMS-less Zenchantments with 1.16.1/1.16.2.
I'll look into it, although I have no idea on what could be the cause there, so I cannot guarantee that it will be fixed anytime soon.
Does `/ench info` on the tool output what is expected?

**Comment by Smash-Nerd** [comment] 2020-12-17 20:30
Yeah it pops out with what it should. 
"
Enchantment Info:
Bind: Keeps items with this enchantment in your inventory after death
"

Weird. I'll keep fishing.

**Comment by Smash-Nerd** [comment] 2020-12-17 20:42
Alright, these were the drops I got. When comparing them to the LotS2 section of the Fishing table at the link I previously provided, you'll see that the chances are totally out of wack. However what I did find interesting was I got a single, untenchanted fishing rod. Another interesting thing to note is from the wiki page from this link
https://minecraft.gamepedia.com/Fishing#cite_note-Treasure-2
"(...) Enchantment probabilities are the same as a level-30 enchantment on an enchanting table. These can also include treasure enchantments that are unavailable via an enchanting table."
It may have something to do with that, but IDK.

![Uploading 2020-12-17_15.38.03.png…]()

**Comment by Geolykt** [comment] 2020-12-17 20:53
I'll look into it, thanks. however the fishing rod isn't anything interesting on it's own due to it being most likely a junk fish.

Do you have anything else that could modify the fishing loot table?

**Comment by Smash-Nerd** [comment] 2020-12-17 20:54
I'm not really a programmer so no. I guess I could try an unenchanted rod and see where that gets me. The wiki says its a 5% chance for a loot pull without LOTS. I'll see if that stacks up to what we've been seeing so far.

**Comment by Smash-Nerd** [comment] 2020-12-17 21:08
I've just recalled something

When we were running Upwards compatible zenchantments, my first pull was an Enchanted book. And something I've just noticed is I have not pulled a single item from the Treasure table. The fishing rod is also in the junk table, so the Treasure table is totally untouched.

Also i've gone through half this unenchanted rod and still no sign of any treasure.

**Comment by Smash-Nerd** [comment] 2020-12-25 00:01
Wait it fixed itself. IDK how tho.

**Comment by Geolykt** [comment] 2020-12-25 09:33
Then I'll close the issue, but it was one strange one

**Closed by Geolykt** 2020-12-25 09:33 UTC
Labels: bug:possible

**Comment by Smash-Nerd** [comment] 2020-12-29 02:00
Extremely. Maybe fishing works differently from when it did in 1.14?
